# Generated by Django 3.0.5 on 2020-08-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.AddField(
            model_name='data',
            name='date_of_birth',
            field=models.CharField(default='10/6/2001', max_length=15),
        ),
    ]
